import '@shoelace-style/shoelace/dist/components/button/button.js'
import '@shoelace-style/shoelace/dist/components/card/card.js'
import '@shoelace-style/shoelace/dist/components/checkbox/checkbox.js'
import '@shoelace-style/shoelace/dist/components/input/input.js'
import '@shoelace-style/shoelace/dist/components/textarea/textarea.js'
//import '@shoelace-style/shoelace/dist/components/menu-item/menu-item.js'
//import '@shoelace-style/shoelace/dist/components/progress-bar/progress-bar.js'
//import '@shoelace-style/shoelace/dist/components/range/range.js'
//import '@shoelace-style/shoelace/dist/components/select/select.js'
import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path.js'
setBasePath('.')